# Generated by Django 4.2.3 on 2026-02-17 19:14

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.CharField(editable=False, help_text='Auto-generated 4-digit unique ID', max_length=4, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 15 digits allowed.", regex='^\\+?1?\\d{9,15}$')])),
                ('plan_type', models.CharField(choices=[('LUNCH_ONLY', 'Lunch Only'), ('DINNER_ONLY', 'Dinner Only'), ('BOTH', 'Both (Lunch + Dinner)')], max_length=15)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('lunch_time', models.TimeField(help_text='Preferred lunch time')),
                ('dinner_time', models.TimeField(help_text='Preferred dinner time')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['customer_id'], name='core_custom_custome_352aed_idx'), models.Index(fields=['is_active'], name='core_custom_is_acti_4a3f48_idx')],
            },
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('meal_type', models.CharField(choices=[('LUNCH', 'Lunch'), ('DINNER', 'Dinner')], max_length=10)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='core.customer')),
            ],
            options={
                'ordering': ['-date', '-marked_at'],
                'indexes': [models.Index(fields=['date', 'meal_type'], name='core_attend_date_912e6f_idx'), models.Index(fields=['customer', 'date'], name='core_attend_custome_01744f_idx')],
                'unique_together': {('customer', 'date', 'meal_type')},
            },
        ),
    ]
